import type { StudyExercise } from './types';

export const STUDY_EXERCISES: StudyExercise[] = [
  {
    id: 'continuidade-producao-t4', origin: 'usuario', operation: 'analyze', answerKind: 'text',
    prompt: 'Considere f(t)={35t²−50t+120, se 0≤t≤4; −15t²+150t, se 4<t≤8}. I. f é contínua em [0,8]. II. Apresenta descontinuidade removível em t=4. Analise as asserções.',
    expected: 'I e II são falsas',
    explanation: 'Em t=4, f(4)=480 e o limite pela esquerda vale 480, enquanto o limite pela direita vale 360. Como os limites laterais são diferentes, o limite bilateral não existe e a função não é contínua em t=4. A descontinuidade é do tipo salto, não removível.',
    relatedContentReason: 'É necessário comparar os limites laterais no ponto em que muda a lei da função e classificar a descontinuidade.',
    topicIds: ['continuidade.funcoes-por-partes','continuidade.limites-laterais','continuidade.salto'], primaryTopicId: 'continuidade.funcoes-por-partes', difficulty: 'intermediario',
    sourceRefs: [{ imageName: 'questao-continuidade-producao.png' }, { materialId: 'slides-aula4-mod2', page: 8 }], tags: ['função por partes','limites laterais','salto'],
  },
  {
    id: 'limite-computadores-x9', origin: 'usuario', operation: 'limit', answerKind: 'expression',
    prompt: 'Uma fábrica modela a quantidade m de computadores por dia por m=(x²−81)/(x−9). Determine a meta quando x tende ao nono dia de treinamento.',
    expression: '(x^2-81)/(x-9)', target: '9', expected: '18',
    explanation: 'Fatorando a diferença de quadrados: x²−81=(x−9)(x+9). Para x diferente de 9, cancela-se x−9, ficando x+9. Portanto, quando x tende a 9, o limite é 18.',
    relatedContentReason: 'A substituição direta gera 0/0; a fatoração e o cancelamento removem a indeterminação antes de calcular o limite.',
    topicIds: ['limites.fatoracao-cancelamento','limites.propriedades'], primaryTopicId: 'limites.fatoracao-cancelamento', difficulty: 'basico',
    sourceRefs: [{ imageName: 'questao-computadores-limite.png' }, { materialId: 'unidade2calc2', page: 35 }], tags: ['diferença de quadrados','indeterminação 0/0','cancelamento'],
  },
  {
    id: 'limite-ohm-r-zero-direita', origin: 'usuario', operation: 'limit', answerKind: 'text',
    prompt: 'Pela Lei de Ohm I=V/R, mantendo V>0 constante, o que ocorre com a corrente quando a resistência tende a zero pela direita, R→0+?',
    expression: 'V/R', target: '0', direction: '+', expected: 'a corrente tende a +infinito',
    explanation: 'Com V positiva e constante, dividir V por valores positivos de R cada vez menores faz I crescer sem limite. Assim, o limite lateral direito da corrente é +∞.',
    relatedContentReason: 'O problema exige interpretar um limite infinito lateral em uma aplicação física.',
    topicIds: ['limites.infinitos','limites.laterais','limites.aplicacoes'], primaryTopicId: 'limites.infinitos', difficulty: 'basico',
    sourceRefs: [{ imageName: 'questao-lei-ohm.png' }, { materialId: 'slides-unidade2', page: 3 }], tags: ['Lei de Ohm','limite lateral direito','infinito'],
  },
  {
    id: 'continuidade-partes-x0', origin: 'usuario', operation: 'analyze', answerKind: 'text',
    prompt: 'Se f(x)={3, se x<0; 3x+3, se x≥0}, analise: I. o limite em 0 não existe porque os limites laterais são distintos; II. os limites laterais existem e são iguais; III. f é contínua em x=0.',
    expected: 'II e III',
    explanation: 'Pela esquerda, f(x)=3 e o limite é 3. Pela direita, 3x+3 tende a 3. Além disso f(0)=3. Logo os limites laterais existem, são iguais e coincidem com o valor da função; II e III são verdadeiras.',
    relatedContentReason: 'A continuidade de uma função por partes no ponto de troca depende dos dois limites laterais e do valor da função.',
    topicIds: ['continuidade.funcoes-por-partes','continuidade.limites-laterais','continuidade.definicao'], primaryTopicId: 'continuidade.funcoes-por-partes', difficulty: 'basico',
    sourceRefs: [{ imageName: 'questao-continuidade-x0.png' }, { materialId: 'unidade2calc2', page: 52 }], tags: ['função por partes','continuidade em um ponto'],
  },
  {
    id: 'limite-racional-alternativas', origin: 'usuario', operation: 'limit', answerKind: 'single-choice',
    prompt: 'Para f(x)=(x²−4x+4)/(x²+3x−6), assinale a alternativa correta.', expression: '(x^2-4*x+4)/(x^2+3*x-6)',
    options: [
      { id: 'a', label: 'lim x→0 f(x)=3' }, { id: 'b', label: 'lim x→1 f(x)=−1' },
      { id: 'c', label: 'lim x→2 f(x)=0' }, { id: 'd', label: 'lim x→6 f(x)=−3' },
      { id: 'e', label: 'lim x→0 f(x)=0' },
    ], correctOptionIds: ['c'], expected: '0', target: '2',
    explanation: 'Em x=2 o denominador vale 4, portanto a substituição direta é válida. O numerador vale 4−8+4=0, de modo que o limite é 0.',
    relatedContentReason: 'A questão verifica quando a substituição direta pode ser aplicada às propriedades de limites de funções racionais.',
    topicIds: ['limites.propriedades'], primaryTopicId: 'limites.propriedades', difficulty: 'basico',
    sourceRefs: [{ imageName: 'questao-racional-alternativas.png' }, { materialId: 'unidade2calc2', page: 12 }], tags: ['função racional','substituição direta'],
  },
  {
    id: 'derivada-populacao-exponencial', origin: 'usuario', operation: 'differentiate', answerKind: 'text',
    prompt: 'Para P(t)=10e^(0,6t), analise: I. a taxa de variação pode ser determinada porque P é diferenciável; II. P′ é obtida apenas pela regra de multiplicação por escalar; III. P é composição de função afim e exponencial; IV. em t=4 a taxa é aproximadamente 66 peixes/mês.',
    expression: '10*exp(0.6*t)', expected: 'I, III e IV',
    explanation: 'P′(t)=6e^(0,6t). Além da multiplicação por constante, a derivação usa a regra da cadeia na exponencial composta. Em t=4, P′(4)=6e^2,4≈66,14. Portanto I, III e IV são verdadeiras.',
    relatedContentReason: 'Relaciona derivada exponencial, composição de funções, regra da cadeia e interpretação como taxa de variação.',
    topicIds: ['derivadas.exponenciais-logaritmicas','derivadas.cadeia','derivadas.definicao-taxa-variacao'], primaryTopicId: 'derivadas.exponenciais-logaritmicas', difficulty: 'intermediario',
    sourceRefs: [{ imageName: 'questao-populacao-peixes.png' }, { materialId: 'aula3-unid3', page: 7 }, { materialId: 'mod3-aula3', page: 6 }], tags: ['exponencial','regra da cadeia','taxa de variação'],
  },
  {
    id: 'derivada-tangente-polinomio', origin: 'usuario', operation: 'differentiate', answerKind: 'single-choice',
    prompt: 'Determine a primeira derivada de H(t)=tg(t)+3t²−t+1.', expression: 'tan(t)+3*t^2-t+1',
    options: [
      { id: 'a', label: 'sec³(t)+6t−1' }, { id: 'b', label: 'sec²(t)+6t²−1' },
      { id: 'c', label: 'sec²(t)+6t' }, { id: 'd', label: 'sec²(t)+6t−1' },
      { id: 'e', label: '−sec²(t)+6t−1' },
    ], correctOptionIds: ['d'], expected: 'sec(t)^2+6*t-1',
    explanation: 'Derivando termo a termo: (tg t)′=sec²t, (3t²)′=6t, (−t)′=−1 e a constante deriva para zero. Logo H′(t)=sec²t+6t−1.',
    relatedContentReason: 'A resolução combina a derivada trigonométrica da tangente com linearidade e regra da potência.',
    topicIds: ['derivadas.trigonometricas','derivadas.linearidade','derivadas.potencia'], primaryTopicId: 'derivadas.trigonometricas', difficulty: 'basico',
    sourceRefs: [{ imageName: 'questao-derivada-tangente.png' }, { materialId: 'mod3-aula3', page: 7 }], tags: ['tangente','secante','regra da potência'],
  },
  {
    id: 'derivacao-implicita-circulo-tangente', origin: 'usuario', operation: 'differentiate', answerKind: 'single-choice',
    prompt: 'Para a curva x²+y²=5, determine a equação da reta tangente no ponto (1,2).', expression: 'x^2+y^2=5',
    options: [
      { id: 'a', label: 'y=2x+5' }, { id: 'b', label: 'y=−x+5' }, { id: 'c', label: 'y=(1/2)x+2/5' },
      { id: 'd', label: 'y=(1/2)x+2' }, { id: 'e', label: 'y=−(1/2)x+5/2' },
    ], correctOptionIds: ['e'], expected: '-x/2+5/2',
    explanation: 'Derivando implicitamente: 2x+2y y′=0, então y′=−x/y. Em (1,2), a inclinação é −1/2. Pela forma ponto-inclinação, y−2=−(1/2)(x−1), isto é, y=−x/2+5/2.',
    relatedContentReason: 'É preciso usar derivação implícita para obter a inclinação e depois a equação da reta tangente.',
    topicIds: ['derivadas.implicita','derivadas.cadeia','derivadas.reta-tangente'], primaryTopicId: 'derivadas.implicita', difficulty: 'intermediario',
    sourceRefs: [{ imageName: 'questao-circulo-reta-tangente.png' }, { materialId: 'aula3-mod3', page: 5 }], tags: ['derivação implícita','círculo','reta tangente'],
  },
  {
    id: 'regras-derivacao-afirmacoes-inconsistente', origin: 'usuario', operation: 'differentiate', answerKind: 'text',
    prompt: 'Analise quatro afirmações de derivação: I. para x cos x+tg x é dada cos x+x sen x+sec²x; II. para 5x² ln x é 10x ln x+5x; III. para (√x+1)/x³ é (−5√x−6)/(2x⁴); IV. para x²e^x é 2xe^x. Quais estão matematicamente corretas?',
    expected: 'II e III',
    explanation: 'I é falsa: pela regra do produto, (x cos x)′=cos x−x sen x. II é verdadeira pela regra do produto. III é verdadeira após reescrever em potências e derivar. IV é falsa porque (x²e^x)′=2xe^x+x²e^x. Assim, matematicamente, apenas II e III são verdadeiras.',
    relatedContentReason: 'A questão exige distinguir e aplicar corretamente regra do produto, derivadas trigonométricas, logarítmicas, potências e exponencial.',
    topicIds: ['derivadas.produto','derivadas.trigonometricas','derivadas.exponenciais-logaritmicas','derivadas.potencia'], primaryTopicId: 'derivadas.produto', difficulty: 'avancado',
    sourceRefs: [{ imageName: 'questao-afirmacoes-derivacao.png' }, { materialId: 'aula3-unid3', page: 3 }], tags: ['regra do produto','inconsistência de alternativa'],
    warning: 'O conjunto de alternativas exibido na plataforma de origem não contém “II e III”, que é o resultado matemático. A alternativa “I, II e III” pode ter sido a pretendida caso o sinal de I tenha sido digitado incorretamente, mas isso é apenas uma inferência sobre a plataforma, não o resultado matemático.',
  },
  {
    id: 'derivada-cosseno-exponencial', origin: 'usuario', operation: 'differentiate', answerKind: 'single-choice',
    prompt: 'Determine a derivada de primeira ordem de f(x)=cos x+e^x+3.', expression: 'cos(x)+exp(x)+3',
    options: [
      { id: 'a', label: 'cos²x+e^x' }, { id: 'b', label: '−sen²x+e^x' }, { id: 'c', label: 'cos x+e^x' },
      { id: 'd', label: '−sen x−e^x' }, { id: 'e', label: '−sen x+e^x' },
    ], correctOptionIds: ['e'], expected: '-sin(x)+exp(x)',
    explanation: 'A derivada de cos x é −sen x, a derivada de e^x é e^x e a derivada da constante 3 é zero. Portanto f′(x)=−sen x+e^x.',
    relatedContentReason: 'A questão reúne derivadas elementares trigonométrica, exponencial e de constante.',
    topicIds: ['derivadas.trigonometricas','derivadas.exponenciais-logaritmicas','derivadas.linearidade'], primaryTopicId: 'derivadas.trigonometricas', difficulty: 'basico',
    sourceRefs: [{ imageName: 'questao-cosseno-exponencial.png' }, { materialId: 'mod3-aula3', page: 6 }], tags: ['cosseno','exponencial','constante'],
  },
];
