import type { StudyExercise } from './types';

export const STUDY_EXERCISES: StudyExercise[] = [
  {
    id: 'continuidade-producao-t4', origin: 'usuario', operation: 'analyze', answerKind: 'text',
    prompt: 'Considere f(t)={35t²−50t+120, se 0≤t≤4; −15t²+150t, se 4<t≤8}. I. f é contínua em [0,8]. II. Apresenta descontinuidade removível em t=4. Analise as asserções.',
    expected: 'I e II são falsas',
    explanation: 'Em t=4, f(4)=480 e o limite pela esquerda vale 480, enquanto o limite pela direita vale 360. Como os limites laterais são diferentes, o limite bilateral não existe e a função não é contínua em t=4. A descontinuidade é do tipo salto, não removível.',
    relatedContentReason: 'É necessário comparar os limites laterais no ponto em que muda a lei da função e classificar a descontinuidade.',
    topicIds: ['continuidade.funcoes-por-partes','continuidade.limites-laterais','continuidade.salto'], primaryTopicId: 'continuidade.funcoes-por-partes', difficulty: 'intermediario',
    sourceRefs: [{ imageName: 'questao-continuidade-producao.png' }, { materialId: 'slides-aula4-mod2', page: 8 }], tags: ['função por partes','limites laterais','salto'],
  },
  {
    id: 'limite-computadores-x9', origin: 'usuario', operation: 'limit', answerKind: 'expression',
    prompt: 'Uma fábrica modela a quantidade m de computadores por dia por m=(x²−81)/(x−9). Determine a meta quando x tende ao nono dia de treinamento.',
    expression: '(x^2-81)/(x-9)', target: '9', expected: '18',
    explanation: 'Fatorando a diferença de quadrados: x²−81=(x−9)(x+9). Para x diferente de 9, cancela-se x−9, ficando x+9. Portanto, quando x tende a 9, o limite é 18.',
    relatedContentReason: 'A substituição direta gera 0/0; a fatoração e o cancelamento removem a indeterminação antes de calcular o limite.',
    topicIds: ['limites.fatoracao-cancelamento','limites.propriedades'], primaryTopicId: 'limites.fatoracao-cancelamento', difficulty: 'basico',
    sourceRefs: [{ imageName: 'questao-computadores-limite.png' }, { materialId: 'unidade2calc2', page: 35 }], tags: ['diferença de quadrados','indeterminação 0/0','cancelamento'],
  },
  {
    id: 'limite-ohm-r-zero-direita', origin: 'usuario', operation: 'limit', answerKind: 'text',
    prompt: 'Pela Lei de Ohm I=V/R, mantendo V>0 constante, o que ocorre com a corrente quando a resistência tende a zero pela direita, R→0+?',
    expression: 'V/R', target: '0', direction: '+', expected: 'a corrente tende a +infinito',
    explanation: 'Com V positiva e constante, dividir V por valores positivos de R cada vez menores faz I crescer sem limite. Assim, o limite lateral direito da corrente é +∞.',
    relatedContentReason: 'O problema exige interpretar um limite infinito lateral em uma aplicação física.',
    topicIds: ['limites.infinitos','limites.laterais','limites.aplicacoes'], primaryTopicId: 'limites.infinitos', difficulty: 'basico',
    sourceRefs: [{ imageName: 'questao-lei-ohm.png' }, { materialId: 'slides-unidade2', page: 3 }], tags: ['Lei de Ohm','limite lateral direito','infinito'],
  },
  {
    id: 'continuidade-partes-x0', origin: 'usuario', operation: 'analyze', answerKind: 'text',
    prompt: 'Se f(x)={3, se x<0; 3x+3, se x≥0}, analise: I. o limite em 0 não existe porque os limites laterais são distintos; II. os limites laterais existem e são iguais; III. f é contínua em x=0.',
    expected: 'II e III',
    explanation: 'Pela esquerda, f(x)=3 e o limite é 3. Pela direita, 3x+3 tende a 3. Além disso f(0)=3. Logo os limites laterais existem, são iguais e coincidem com o valor da função; II e III são verdadeiras.',
    relatedContentReason: 'A continuidade de uma função por partes no ponto de troca depende dos dois limites laterais e do valor da função.',
    topicIds: ['continuidade.funcoes-por-partes','continuidade.limites-laterais','continuidade.definicao'], primaryTopicId: 'continuidade.funcoes-por-partes', difficulty: 'basico',
    sourceRefs: [{ imageName: 'questao-continuidade-x0.png' }, { materialId: 'unidade2calc2', page: 52 }], tags: ['função por partes','continuidade em um ponto'],
  },
  {
    id: 'limite-racional-alternativas', origin: 'usuario', operation: 'limit', answerKind: 'single-choice',
    prompt: 'Para f(x)=(x²−4x+4)/(x²+3x−6), assinale a alternativa correta.', expression: '(x^2-4*x+4)/(x^2+3*x-6)',
    options: [
      { id: 'a', label: 'lim x→0 f(x)=3' }, { id: 'b', label: 'lim x→1 f(x)=−1' },
      { id: 'c', label: 'lim x→2 f(x)=0' }, { id: 'd', label: 'lim x→6 f(x)=−3' },
      { id: 'e', label: 'lim x→0 f(x)=0' },
    ], correctOptionIds: ['c'], expected: '0', target: '2',
    explanation: 'Em x=2 o denominador vale 4, portanto a substituição direta é válida. O numerador vale 4−8+4=0, de modo que o limite é 0.',
    relatedContentReason: 'A questão verifica quando a substituição direta pode ser aplicada às propriedades de limites de funções racionais.',
    topicIds: ['limites.propriedades'], primaryTopicId: 'limites.propriedades', difficulty: 'basico',
    sourceRefs: [{ imageName: 'questao-racional-alternativas.png' }, { materialId: 'unidade2calc2', page: 12 }], tags: ['função racional','substituição direta'],
  },
  {
    id: 'derivada-populacao-exponencial', origin: 'usuario', operation: 'differentiate', answerKind: 'text',
    prompt: 'Para P(t)=10e^(0,6t), analise: I. a taxa de variação pode ser determinada porque P é diferenciável; II. P′ é obtida apenas pela regra de multiplicação por escalar; III. P é composição de função afim e exponencial; IV. em t=4 a taxa é aproximadamente 66 peixes/mês.',
    expression: '10*exp(0.6*t)', expected: 'I, III e IV',
    explanation: 'P′(t)=6e^(0,6t). Além da multiplicação por constante, a derivação usa a regra da cadeia na exponencial composta. Em t=4, P′(4)=6e^2,4≈66,14. Portanto I, III e IV são verdadeiras.',
    relatedContentReason: 'Relaciona derivada exponencial, composição de funções, regra da cadeia e interpretação como taxa de variação.',
    topicIds: ['derivadas.exponenciais-logaritmicas','derivadas.cadeia','derivadas.definicao-taxa-variacao'], primaryTopicId: 'derivadas.exponenciais-logaritmicas', difficulty: 'intermediario',
    sourceRefs: [{ imageName: 'questao-populacao-peixes.png' }, { materialId: 'aula3-unid3', page: 7 }, { materialId: 'mod3-aula3', page: 6 }], tags: ['exponencial','regra da cadeia','taxa de variação'],
  },
  {
    id: 'derivada-tangente-polinomio', origin: 'usuario', operation: 'differentiate', answerKind: 'single-choice',
    prompt: 'Determine a primeira derivada de H(t)=tg(t)+3t²−t+1.', expression: 'tan(t)+3*t^2-t+1',
    options: [
      { id: 'a', label: 'sec³(t)+6t−1' }, { id: 'b', label: 'sec²(t)+6t²−1' },
      { id: 'c', label: 'sec²(t)+6t' }, { id: 'd', label: 'sec²(t)+6t−1' },
      { id: 'e', label: '−sec²(t)+6t−1' },
    ], correctOptionIds: ['d'], expected: 'sec(t)^2+6*t-1',
    explanation: 'Derivando termo a termo: (tg t)′=sec²t, (3t²)′=6t, (−t)′=−1 e a constante deriva para zero. Logo H′(t)=sec²t+6t−1.',
    relatedContentReason: 'A resolução combina a derivada trigonométrica da tangente com linearidade e regra da potência.',
    topicIds: ['derivadas.trigonometricas','derivadas.linearidade','derivadas.potencia'], primaryTopicId: 'derivadas.trigonometricas', difficulty: 'basico',
    sourceRefs: [{ imageName: 'questao-derivada-tangente.png' }, { materialId: 'mod3-aula3', page: 7 }], tags: ['tangente','secante','regra da potência'],
  },
  {
    id: 'derivacao-implicita-circulo-tangente', origin: 'usuario', operation: 'differentiate', answerKind: 'single-choice',
    prompt: 'Para a curva x²+y²=5, determine a equação da reta tangente no ponto (1,2).', expression: 'x^2+y^2=5',
    options: [
      { id: 'a', label: 'y=2x+5' }, { id: 'b', label: 'y=−x+5' }, { id: 'c', label: 'y=(1/2)x+2/5' },
      { id: 'd', label: 'y=(1/2)x+2' }, { id: 'e', label: 'y=−(1/2)x+5/2' },
    ], correctOptionIds: ['e'], expected: '-x/2+5/2',
    explanation: 'Derivando implicitamente: 2x+2y y′=0, então y′=−x/y. Em (1,2), a inclinação é −1/2. Pela forma ponto-inclinação, y−2=−(1/2)(x−1), isto é, y=−x/2+5/2.',
    relatedContentReason: 'É preciso usar derivação implícita para obter a inclinação e depois a equação da reta tangente.',
    topicIds: ['derivadas.implicita','derivadas.cadeia','derivadas.reta-tangente'], primaryTopicId: 'derivadas.implicita', difficulty: 'intermediario',
    sourceRefs: [{ imageName: 'questao-circulo-reta-tangente.png' }, { materialId: 'aula3-mod3', page: 5 }], tags: ['derivação implícita','círculo','reta tangente'],
  },
  {
    id: 'regras-derivacao-afirmacoes-inconsistente', origin: 'usuario', operation: 'differentiate', answerKind: 'text',
    prompt: 'Analise quatro afirmações de derivação: I. para x cos x+tg x é dada cos x+x sen x+sec²x; II. para 5x² ln x é 10x ln x+5x; III. para (√x+1)/x³ é (−5√x−6)/(2x⁴); IV. para x²e^x é 2xe^x. Quais estão matematicamente corretas?',
    expected: 'II e III',
    explanation: 'I é falsa: pela regra do produto, (x cos x)′=cos x−x sen x. II é verdadeira pela regra do produto. III é verdadeira após reescrever em potências e derivar. IV é falsa porque (x²e^x)′=2xe^x+x²e^x. Assim, matematicamente, apenas II e III são verdadeiras.',
    relatedContentReason: 'A questão exige distinguir e aplicar corretamente regra do produto, derivadas trigonométricas, logarítmicas, potências e exponencial.',
    topicIds: ['derivadas.produto','derivadas.trigonometricas','derivadas.exponenciais-logaritmicas','derivadas.potencia'], primaryTopicId: 'derivadas.produto', difficulty: 'avancado',
    sourceRefs: [{ imageName: 'questao-afirmacoes-derivacao.png' }, { materialId: 'aula3-unid3', page: 3 }], tags: ['regra do produto','inconsistência de alternativa'],
    warning: 'O conjunto de alternativas exibido na plataforma de origem não contém “II e III”, que é o resultado matemático. A alternativa “I, II e III” pode ter sido a pretendida caso o sinal de I tenha sido digitado incorretamente, mas isso é apenas uma inferência sobre a plataforma, não o resultado matemático.',
  },
  {
    id: 'derivada-cosseno-exponencial', origin: 'usuario', operation: 'differentiate', answerKind: 'single-choice',
    prompt: 'Determine a derivada de primeira ordem de f(x)=cos x+e^x+3.', expression: 'cos(x)+exp(x)+3',
    options: [
      { id: 'a', label: 'cos²x+e^x' }, { id: 'b', label: '−sen²x+e^x' }, { id: 'c', label: 'cos x+e^x' },
      { id: 'd', label: '−sen x−e^x' }, { id: 'e', label: '−sen x+e^x' },
    ], correctOptionIds: ['e'], expected: '-sin(x)+exp(x)',
    explanation: 'A derivada de cos x é −sen x, a derivada de e^x é e^x e a derivada da constante 3 é zero. Portanto f′(x)=−sen x+e^x.',
    relatedContentReason: 'A questão reúne derivadas elementares trigonométrica, exponencial e de constante.',
    topicIds: ['derivadas.trigonometricas','derivadas.exponenciais-logaritmicas','derivadas.linearidade'], primaryTopicId: 'derivadas.trigonometricas', difficulty: 'basico',
    sourceRefs: [{ imageName: 'questao-cosseno-exponencial.png' }, { materialId: 'mod3-aula3', page: 6 }], tags: ['cosseno','exponencial','constante'],
  },
  {
    id: 'taxa-bola-raio', origin: 'material', operation: 'analyze', answerKind: 'text',
    prompt: 'Uma bola de futebol é aproximada por uma esfera e recebe ar a 100 cm³/s. Quão rápido o raio aumenta quando o diâmetro é 8 cm?',
    expected: '25/(16π) cm/s, aproximadamente 0,497 cm/s',
    acceptedAnswers: ['25/(16*pi) cm/s', '25/(16π) cm/s', '0,497 cm/s', '0.497 cm/s'],
    explanation: 'Para V=(4/3)πr³, derivando em relação ao tempo obtemos dV/dt=4πr²·dr/dt. Com dV/dt=100 e r=4, segue dr/dt=100/(64π)=25/(16π) cm/s≈0,497 cm/s.',
    relatedContentReason: 'É um exemplo direto de taxas relacionadas, com regra da cadeia aplicada ao volume de uma esfera.',
    topicIds: ['derivadas.taxas-relacionadas','derivadas.cadeia','derivadas.definicao-taxa-variacao'], primaryTopicId: 'derivadas.taxas-relacionadas', difficulty: 'intermediario',
    sourceRefs: [{ materialId: 'mod4-aula1-taxas-relacionadas', page: 4 }, { materialId: 'mod4-unidade-completa', page: 3 }], tags: ['taxas relacionadas','esfera','volume','regra da cadeia'],
  },
  {
    id: 'taxa-escada-base', origin: 'material', operation: 'analyze', answerKind: 'text',
    prompt: 'Uma escada de 1,3 m está apoiada em uma parede. O topo desce a 0,2 m/s. Com que rapidez a base se afasta da parede quando o topo está 0,5 m acima do chão?',
    expected: 'aproximadamente 0,083 m/s',
    acceptedAnswers: ['0,083 m/s', '0.083 m/s'],
    explanation: 'Da relação x²+y²=1,69, quando y=0,5 resulta x=1,2. Derivando: 2x dx/dt+2y dy/dt=0. Com dy/dt=−0,2, obtemos dx/dt=−(0,5/1,2)(−0,2)≈0,083 m/s.',
    relatedContentReason: 'O problema exige relacionar duas taxas por meio do teorema de Pitágoras e derivação em relação ao tempo.',
    topicIds: ['derivadas.taxas-relacionadas','derivadas.cadeia'], primaryTopicId: 'derivadas.taxas-relacionadas', difficulty: 'intermediario',
    sourceRefs: [{ materialId: 'mod4-aula1-taxas-relacionadas', page: 6 }, { materialId: 'mod4-unidade-completa', page: 5 }], tags: ['taxas relacionadas','escada','Pitágoras'],
  },
  {
    id: 'taxa-calha-nivel', origin: 'material', operation: 'analyze', answerKind: 'text',
    prompt: 'Uma calha de 20 m tem extremidades triangulares de 5 m de base por 2 m de altura e recebe água a 8 m³/min. Com que rapidez o nível sobe quando a profundidade é 1 m?',
    expected: '4/25 m/min, isto é, 0,16 m/min',
    acceptedAnswers: ['4/25 m/min', '0,16 m/min', '0.16 m/min'],
    explanation: 'Por semelhança de triângulos, b=(5/2)h. Como V=(1/2)bh·20, segue V=25h². Derivando, dV/dt=50h·dh/dt. Com dV/dt=8 e h=1, dh/dt=8/50=4/25=0,16 m/min.',
    relatedContentReason: 'Combina modelagem geométrica, semelhança de triângulos e derivação de taxas relacionadas.',
    topicIds: ['derivadas.taxas-relacionadas','derivadas.cadeia'], primaryTopicId: 'derivadas.taxas-relacionadas', difficulty: 'intermediario',
    sourceRefs: [{ materialId: 'mod4-aula1-taxas-relacionadas', page: 7 }, { materialId: 'mod4-unidade-completa', page: 7 }], tags: ['taxas relacionadas','calha','semelhança de triângulos'],
  },
  {
    id: 'taxa-tanque-conico', origin: 'material', operation: 'analyze', answerKind: 'text',
    prompt: 'Um reservatório cônico invertido tem 8 m de altura e 6 m de diâmetro no topo. Vazem 10 000 cm³/min e o nível deve subir a 20 cm/min quando h=2 m. Qual deve ser a taxa de bombeamento para dentro?',
    expected: '112500π+10000 cm³/min, aproximadamente 363429,2 cm³/min',
    acceptedAnswers: ['112500*pi+10000 cm^3/min', '363429,2 cm³/min', '363429.2 cm³/min'],
    explanation: 'Pela semelhança de triângulos, r=3h/8. Assim V=(1/3)πr²h=(3/64)πh³ e dV/dt=(9/64)πh²·dh/dt. Para h=200 cm e dh/dt=20 cm/min, dV/dt=112500π. Como dV/dt=T−10000, T=112500π+10000≈363429,2 cm³/min.',
    relatedContentReason: 'É o problema-síntese de taxas relacionadas do módulo e exige modelagem do cone, semelhança e balanço de vazões.',
    topicIds: ['derivadas.taxas-relacionadas','derivadas.cadeia'], primaryTopicId: 'derivadas.taxas-relacionadas', difficulty: 'avancado',
    sourceRefs: [{ materialId: 'mod4-aula5-encerramento', page: 6 }, { materialId: 'mod4-unidade-completa', page: 62 }], tags: ['taxas relacionadas','cone','vazão','semelhança'],
  },
  {
    id: 'otimizacao-caixa-papelao', origin: 'material', operation: 'analyze', answerKind: 'text',
    prompt: 'De uma folha de papelão 12 cm×24 cm são cortados quadrados iguais de lado x nos quatro cantos para formar uma caixa sem tampa. Qual x maximiza o volume?',
    expected: 'x=6−2√3 cm, aproximadamente 2,54 cm',
    acceptedAnswers: ['6-2*sqrt(3) cm', '6−2√3 cm', '2,54 cm', '2.54 cm'],
    explanation: 'O volume é V(x)=(24−2x)(12−2x)x=288x−72x²+4x³, com 0≤x≤6. De V′(x)=288−144x+12x² surgem x=6±2√3; apenas 6−2√3 pertence ao domínio. Como V″ nesse ponto é negativa e as extremidades têm volume zero, esse é o máximo global.',
    relatedContentReason: 'É o exemplo central de otimização do módulo, combinando modelagem, domínio, pontos críticos e teste da segunda derivada.',
    topicIds: ['derivadas.otimizacao','derivadas.pontos-criticos-extremos','derivadas.teste-segunda-derivada'], primaryTopicId: 'derivadas.otimizacao', difficulty: 'avancado',
    sourceRefs: [{ materialId: 'mod4-aula3-otimizacao-testes', page: 9 }, { materialId: 'mod4-unidade-completa', page: 41 }], tags: ['otimização','volume','caixa','ponto crítico'],
  },
  {
    id: 'otimizacao-lucro-maximo', origin: 'material', operation: 'analyze', answerKind: 'text',
    prompt: 'Se C(x)=0,01x³−0,6x²+13x e cada unidade é vendida por R$ 7,00, para qual produção o modelo indica lucro máximo?',
    expected: 'x≈34,14 unidades no modelo contínuo',
    acceptedAnswers: ['34,14', '34.14', 'x=34,14', 'x=34.14'],
    explanation: 'A receita é R(x)=7x e o lucro é L(x)=R−C=−0,01x³+0,6x²−6x. A derivada L′=−0,03x²+1,2x−6 tem pontos críticos em aproximadamente 5,86 e 34,14. Como L″(34,14)<0, o ponto x≈34,14 é máximo local; como L(x)→−∞ para x→+∞, ele é o máximo relevante do modelo.',
    relatedContentReason: 'Aplica derivadas à otimização econômica por meio das funções custo, receita e lucro.',
    topicIds: ['derivadas.otimizacao','derivadas.pontos-criticos-extremos','derivadas.teste-segunda-derivada'], primaryTopicId: 'derivadas.otimizacao', difficulty: 'avancado',
    sourceRefs: [{ materialId: 'mod4-aula5-encerramento', page: 9 }, { materialId: 'mod4-unidade-completa', page: 44 }], tags: ['otimização','lucro','custo','receita'],
  },
  {
    id: 'maximo-minimo-x-dois-tercos', origin: 'material', operation: 'analyze', answerKind: 'text',
    prompt: 'Para f(x)=x^(2/3) em [−2,3], determine os valores máximo e mínimo absolutos.',
    expected: 'mínimo f(0)=0; máximo f(3)=∛9≈2,08',
    acceptedAnswers: ['minimo em x=0 e maximo em x=3', 'f(0)=0 e f(3)=∛9', '0 e 2,08'],
    explanation: 'A derivada não existe em x=0, embora f esteja definida, então 0 é ponto crítico. Comparando f(0)=0 com os extremos f(−2)=∛4 e f(3)=∛9≈2,08, o mínimo absoluto é 0 em x=0 e o máximo absoluto ocorre em x=3.',
    relatedContentReason: 'Exercita a definição de ponto crítico e a comparação com as extremidades de um intervalo fechado.',
    topicIds: ['derivadas.pontos-criticos-extremos'], primaryTopicId: 'derivadas.pontos-criticos-extremos', difficulty: 'intermediario',
    sourceRefs: [{ materialId: 'mod4-unidade-completa', page: 27 }], tags: ['ponto crítico','máximo absoluto','mínimo absoluto','intervalo fechado'],
  },
  {
    id: 'lhospital-cubica-menos-dois', origin: 'material', operation: 'limit', answerKind: 'expression',
    prompt: 'Calcule lim x→−2 (x³+8)/(x+2) usando a regra de L’Hospital.',
    expression: '(x^3+8)/(x+2)', target: '-2', expected: '12',
    explanation: 'A substituição direta produz 0/0. Pela regra de L’Hospital, o limite é lim 3x²/1. Substituindo x=−2, obtemos 3·4=12.',
    relatedContentReason: 'É o primeiro exemplo explícito de aplicação da regra de L’Hospital no material.',
    topicIds: ['limites.lhospital'], primaryTopicId: 'limites.lhospital', difficulty: 'basico',
    sourceRefs: [{ materialId: 'mod4-aula4-lhospital', page: 4 }, { materialId: 'mod4-unidade-completa', page: 49 }], tags: ['L’Hospital','0/0','limite'],
  },
  {
    id: 'lhospital-infinito-linear', origin: 'material', operation: 'limit', answerKind: 'expression',
    prompt: 'Calcule lim x→∞ (10x−9)/(−3+12x) usando a regra de L’Hospital.',
    expression: '(10*x-9)/(-3+12*x)', target: 'oo', expected: '5/6',
    explanation: 'A forma é ∞/∞. Derivando numerador e denominador, o limite passa a 10/12, que simplifica para 5/6.',
    relatedContentReason: 'Exemplifica a aplicação de L’Hospital à indeterminação ∞/∞.',
    topicIds: ['limites.lhospital','limites.no-infinito'], primaryTopicId: 'limites.lhospital', difficulty: 'basico',
    sourceRefs: [{ materialId: 'mod4-aula4-lhospital', page: 5 }, { materialId: 'mod4-unidade-completa', page: 50 }], tags: ['L’Hospital','infinito','∞/∞'],
  },
  {
    id: 'lhospital-corrente-circuito', origin: 'material', operation: 'limit', answerKind: 'text',
    prompt: 'Para I(t)=1/sen(t)−1/t, determine lim t→0⁺ I(t) conforme a estratégia apresentada no módulo.',
    expected: '0',
    explanation: 'A forma inicial é ∞−∞, então primeiro combinamos as frações: I(t)=(t−sen t)/(t sen t), obtendo 0/0. Aplicando L’Hospital e repetindo quando a nova razão ainda é 0/0, o limite resulta 0.',
    relatedContentReason: 'Mostra que formas como ∞−∞ precisam ser transformadas antes da aplicação de L’Hospital e conecta o cálculo de limites a um modelo físico.',
    topicIds: ['limites.lhospital','limites.laterais','limites.aplicacoes'], primaryTopicId: 'limites.lhospital', difficulty: 'avancado',
    sourceRefs: [{ materialId: 'mod4-unidade-completa', page: 58 }], tags: ['L’Hospital','∞−∞','circuito elétrico','limite lateral'],
  },
];
