import type { StudyTopic } from './types';

export const STUDY_TOPICS: StudyTopic[] = [
  { id: 'limites.introducao', group: 'Limites', title: 'Introdução aos limites', summary: 'Comportamento de uma função quando a variável se aproxima de um valor.', essentials: ['O limite descreve o comportamento da função quando x se aproxima de um valor, mesmo quando esse ponto não pertence ao domínio.'] },
  { id: 'limites.laterais', group: 'Limites', title: 'Limites laterais', summary: 'Comportamento pela esquerda e pela direita.', essentials: ['O limite bilateral existe quando os limites pela esquerda e pela direita existem e são iguais.'] },
  { id: 'limites.propriedades', group: 'Limites', title: 'Propriedades de limites', summary: 'Regras algébricas aplicadas a limites existentes.', essentials: ['As propriedades de soma, produto, quociente e potência podem ser usadas quando os limites envolvidos existem; no quociente, o limite do denominador não pode ser zero.'] },
  { id: 'limites.fatoracao-cancelamento', group: 'Limites', title: 'Fatoração e cancelamento', summary: 'Remoção de indeterminações algébricas por fatoração.', essentials: ['Quando a substituição direta conduz a divisão por zero ou outra indeterminação, pode ser necessário fatorar e simplificar antes de substituir.'] },
  { id: 'limites.infinitos', group: 'Limites', title: 'Limites infinitos', summary: 'Casos em que a função cresce ou decresce sem limite.', essentials: ['Limites infinitos descrevem situações em que os valores da função crescem ou decrescem sem cotas ao se aproximar de um ponto.'] },
  { id: 'limites.no-infinito', group: 'Limites', title: 'Limites no infinito', summary: 'Comportamento quando a variável tende a ±∞.', essentials: ['Limites no infinito analisam o comportamento da função quando x cresce ou decresce sem cota.'] },
  { id: 'limites.assintotas', group: 'Limites', title: 'Assíntotas', summary: 'Relação entre limites e retas assintóticas.', essentials: ['Limites infinitos podem indicar assíntotas verticais; limites finitos quando x tende a ±∞ podem indicar assíntotas horizontais.'] },
  { id: 'limites.aplicacoes', group: 'Limites', title: 'Aplicações de limites', summary: 'Modelos e interpretações físicas ou contextuais.', essentials: ['A interpretação do limite deve respeitar o domínio e o significado das grandezas do modelo.'] },
  { id: 'limites.lhospital', group: 'Limites', title: 'Regra de L’Hospital', summary: 'Cálculo de limites indeterminados por derivação do numerador e do denominador.', essentials: ['A regra de L’Hospital é aplicada diretamente às formas 0/0 e ∞/∞ quando as hipóteses de diferenciabilidade são satisfeitas.', 'Outras formas indeterminadas, como 0·∞, ∞−∞ e 1^∞, precisam ser transformadas antes da aplicação da regra.'] },
  { id: 'continuidade.definicao', group: 'Continuidade', title: 'Definição de continuidade', summary: 'Condições para uma função ser contínua em um ponto.', essentials: ['Em x=a, f(a) deve estar definida, o limite de f(x) quando x tende a a deve existir e esse limite deve ser igual a f(a).'] },
  { id: 'continuidade.funcoes-por-partes', group: 'Continuidade', title: 'Funções por partes', summary: 'Continuidade nos pontos em que a lei da função muda.', essentials: ['Em funções definidas por partes, os pontos de mudança da lei de formação exigem análise dos limites laterais.'] },
  { id: 'continuidade.limites-laterais', group: 'Continuidade', title: 'Continuidade e limites laterais', summary: 'Comparação dos limites laterais com o valor da função.', essentials: ['Para continuidade no ponto de junção, os limites laterais devem coincidir entre si e com o valor da função.'] },
  { id: 'continuidade.removivel', group: 'Continuidade', title: 'Descontinuidade removível', summary: 'Descontinuidade corrigível pela redefinição pontual da função.', essentials: ['Quando o limite existe, mas o valor da função está ausente ou não coincide com ele, a descontinuidade pode ser removível.'] },
  { id: 'continuidade.salto', group: 'Continuidade', title: 'Descontinuidade por salto', summary: 'Limites laterais finitos e diferentes.', essentials: ['A descontinuidade do tipo salto ocorre quando os limites laterais existem, mas são diferentes.'] },
  { id: 'continuidade.infinita', group: 'Continuidade', title: 'Descontinuidade infinita', summary: 'Comportamento não limitado próximo ao ponto.', essentials: ['Uma descontinuidade infinita está associada a pelo menos um limite lateral infinito no ponto.'] },
  { id: 'derivadas.definicao-taxa-variacao', group: 'Derivadas', title: 'Derivada e taxa de variação', summary: 'Interpretação da derivada como taxa instantânea.', essentials: ['A derivada pode ser interpretada como taxa de variação e como inclinação da reta tangente.'] },
  { id: 'derivadas.linearidade', group: 'Derivadas', title: 'Linearidade da derivada', summary: 'Soma, diferença e multiplicação por constante.', essentials: ['A derivada de uma soma ou diferença é a soma ou diferença das derivadas, e constantes multiplicativas permanecem como fatores.'] },
  { id: 'derivadas.potencia', group: 'Derivadas', title: 'Regra da potência', summary: 'Derivação de potências da variável.', essentials: ['A regra da potência é uma das regras iniciais usadas para derivar polinômios.'] },
  { id: 'derivadas.produto', group: 'Derivadas', title: 'Regra do produto', summary: 'Derivação do produto de duas funções.', essentials: ['Para um produto de funções deriváveis, é necessário combinar a derivada de cada fator com o outro fator não derivado.'] },
  { id: 'derivadas.quociente', group: 'Derivadas', title: 'Regra do quociente', summary: 'Derivação do quociente de duas funções.', essentials: ['A regra do quociente se aplica quando o denominador não é zero.'] },
  { id: 'derivadas.cadeia', group: 'Derivadas', title: 'Regra da cadeia', summary: 'Derivação de funções compostas.', essentials: ['Na composição de funções, a derivada combina a derivada da função externa com a derivada da função interna.'] },
  { id: 'derivadas.exponenciais-logaritmicas', group: 'Derivadas', title: 'Exponenciais e logarítmicas', summary: 'Regras de derivação para funções exponenciais e logarítmicas.', essentials: ['As funções exponenciais e logarítmicas possuem regras próprias de derivação e podem também exigir regra da cadeia quando compostas.'] },
  { id: 'derivadas.trigonometricas', group: 'Derivadas', title: 'Derivadas trigonométricas', summary: 'Regras de derivação para seno, cosseno, tangente e relacionadas.', essentials: ['As principais funções trigonométricas possuem derivadas específicas; por exemplo, a derivada da tangente envolve secante ao quadrado.'] },
  { id: 'derivadas.implicita', group: 'Derivadas', title: 'Derivação implícita', summary: 'Derivação de relações em que y não está isolado.', essentials: ['Derive os dois membros em relação à variável independente e depois resolva para a derivada; a regra da cadeia é essencial quando y depende de x.'] },
  { id: 'derivadas.reta-tangente', group: 'Derivadas', title: 'Reta tangente', summary: 'Uso da derivada como inclinação da reta tangente.', essentials: ['Após obter a derivada no ponto, use esse valor como inclinação da reta tangente que passa pelo ponto da curva.'] },
  { id: 'derivadas.taxas-relacionadas', group: 'Derivadas', title: 'Taxas relacionadas', summary: 'Relação entre taxas de variação de grandezas dependentes do tempo.', essentials: ['Identifique as variáveis, escreva uma equação que as relacione, derive em relação ao tempo e só então substitua os valores conhecidos.', 'A regra da cadeia aparece porque as grandezas variam em função do tempo.'] },
  { id: 'derivadas.pontos-criticos-extremos', group: 'Derivadas', title: 'Pontos críticos, máximos e mínimos', summary: 'Identificação de pontos críticos e valores extremos locais ou absolutos.', essentials: ['Pontos críticos pertencem ao domínio e ocorrem quando a derivada é zero ou não existe.', 'Em intervalos fechados, extremos absolutos exigem comparar pontos críticos com as extremidades.'] },
  { id: 'derivadas.rolle-valor-medio', group: 'Derivadas', title: 'Rolle e Teorema do Valor Médio', summary: 'Resultados que relacionam continuidade, diferenciabilidade e inclinações.', essentials: ['Rolle garante um ponto interno com derivada zero quando a função é contínua no intervalo fechado, diferenciável no aberto e tem valores iguais nas extremidades.', 'O Teorema do Valor Médio garante um ponto em que a derivada iguala a taxa média de variação no intervalo.'] },
  { id: 'derivadas.crescimento-decrescimento', group: 'Derivadas', title: 'Crescimento e decrescimento', summary: 'Uso do sinal da primeira derivada para descrever o comportamento da função.', essentials: ['Se f′(x)>0 em um intervalo, a função é crescente; se f′(x)<0, é decrescente.'] },
  { id: 'derivadas.teste-primeira-derivada', group: 'Derivadas', title: 'Teste da primeira derivada', summary: 'Classificação de pontos críticos pela mudança de sinal de f′.', essentials: ['Mudança de positivo para negativo indica máximo local; de negativo para positivo indica mínimo local.', 'Sem mudança de sinal, o ponto crítico não é máximo nem mínimo local.'] },
  { id: 'derivadas.teste-segunda-derivada', group: 'Derivadas', title: 'Teste da segunda derivada', summary: 'Classificação de pontos críticos pelo sinal da segunda derivada.', essentials: ['Em um ponto crítico c, f″(c)>0 indica mínimo local e f″(c)<0 indica máximo local.', 'Quando f″(c)=0, o teste é inconclusivo.'] },
  { id: 'derivadas.concavidade-inflexao', group: 'Derivadas', title: 'Concavidade e ponto de inflexão', summary: 'Estudo da concavidade a partir da segunda derivada.', essentials: ['f″(x)>0 indica concavidade para cima e f″(x)<0 concavidade para baixo.', 'Um ponto de inflexão exige mudança de concavidade.'] },
  { id: 'derivadas.otimizacao', group: 'Derivadas', title: 'Problemas de otimização', summary: 'Modelagem de máximos e mínimos sujeitos às condições do problema.', essentials: ['Modele a quantidade a otimizar como função de uma variável, determine o domínio relevante e encontre os pontos críticos.', 'Use os testes de derivadas e, quando necessário, os extremos do domínio para identificar máximo ou mínimo global.'] },
];

export function getTopicById(id: string): StudyTopic | undefined {
  return STUDY_TOPICS.find((topic) => topic.id === id);
}
